#include <stdio.h>
#include "bitwise edit distance alignment single word.h"
#include "bitwise edit distance alignment multiple word clean.h"

//test cases
//string lengths are 8 and 8
//edit distance is 2
/*
char *string1 = "ACGTACGT";
char *string2 = "GACGTACT";
int N = 8;
int M = 8;
*/


//string lengths are 30 and 25
//edit distance is 11
/*
char *string1 = "GTCTTCACGGCCTTCACCACCTACATGTAT";
char *string2 = "GGCCTTCACCACCTACATGTATCCT";
int N = 30;
int M = 25;
*/

//string lengths are 65 and 65
//edit distance = 2

char *string1 = "ACGTACGTTTCGCGAGCAGCTTGAATCGACACGTACGTTTCGCGAGCAGCTTGAAACGACTTAGG";
char *string2 = "ACGTACGTTTCGCGAGCAGCTTGAAACGACACGTACGTTTCGCGAGCAGCTTGGAACGACTTAGG";
int N = 65;
int M = 65;



//string lengths are 255 and 254
//edit distance is 3
/*
char *string1 = "GCTTCCTGACTCCTCATCCACCATCATTTCTGCCTGTACACCATGTTGCCTCACACCTGGCAATAAGAAAACTCATCTTTGTCCTCACTGTAATGGAATAATGTGGGGTTTTTTCTTCATTATGCAGCTTTCCTCTTGATTTTCCTCTTAGTTCTCCTCTTGATTCTCTCTTGATTCACTGTCTTGAAAAGTGCTCTGAATTTTTTTACCCCTTAAGACTTTTGCAAGAAGATGCAGCAGAAGTATGGATGAGGA";
char *string2 = "GCTTCCTGACTCCTCACCACCATCATTTCTGCCTGTACACCATGTTGCCTCACACCTGGCAATAAGAAAACTCATCTTTGTCCTCACTGTAATGGAATAATGTGGGGTTTTTTTCTTCATTATGCAGCTTTCCTCTTGATTTTCCTCTTAGTTCTCCTCTTGATTCTCTCTTGATCACTGTCTTGAAAAGTGCTCTGAATTTTTTTACCCCTTAAGACTTTTGCAAGAAGATGCAGCAGAAGTATGGATGAGGA";
int N = 255;
int M = 254;
*/

//string lengths are 300 and 300
//edit distance is 164
/*
char *string1 = "TTCGCGGAGTGGGATTCTACTGTGGAGTGATGCAGATTTTCCATTAAGATAACTCTAGCGTATACCGGTGTGAATAGTTCCTTCTCGTGCCCCTCACGCAGCGCCCGCAGGGATGCTTCGTCGCTAATTAGCTCGGTACGTAGCTTGCCTCCAATCATAACCGCGAAAGGATTCCCACTTGGACATGCGGCCTACCGGTGCAATCCAAAATTGGCACCTTGCTAATACAGGGCTGCGCGAAATCGTGTGGCGCCCAGCAGAAATAAAAGACCGAAACCGCTACCTAGCCTACGAGGCTTG";
char *string2 = "AGCGTAGTGTAAATGAGAAGGGCGTCGTCGGCGCTCTCGATCTTTCGAGCAGCGCATCTCAACGGCTAAGGATGTCTTTAAGAAAGGACGTAAAGTACCACATGATCTAAAACTGCCGCACCCTTAATCATCGTCGGATTACGAGTTCTCCCATTCGAGATGGCCTTAACGACGTTAAGATACATTCCGTCTCATGTACCACCCGCCGATAAATTCGTCCTCCACAACGACTTTGGAAAAGCGGGACGTGAGAGACTTTGCTACGGCCTCTGAGTAACGACGTACCGTTGGTTGTGACAC";
int N = 300;
int M = 300;
*/



int main (int argc, const char * argv[]) {
  
  int score;
  
  printf("\nString 1: %s",string1);
  printf("\nlength = %d\n", M);
  printf("\nString 2: %s",string2);
  printf("\nlength = %d\n", N);
  
  //use this for single word (64 bit) processing
  //max string1 length is 63 characters
  //score = Edit_Distance_single_word(string1,string2,N,M);
  //printf("\nSingle Word Unit Cost Edit Distance = %d",score);
  
  //use this for strings of any size
  score = Edit_Distance_multiple_word_clean(string1,string2,N,M);
  printf("\n\nMultiple Word Unit Cost Edit Distance = %d\n",score);
  
  return 0;
}
